name: Release CMS
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - "*"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: list of files
        run: ls -la

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
    
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/cms-contentful-app:latest
      
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/cms-contentful-app:latest .

          # Uncomment the line below if you want to also push a specific version tag
          # docker buildx build --platform linux/amd64,linux/arm64 -t your-dockerhub-username/your-image-name:1.0.0 .

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cms-contentful-app:latest
          # Uncomment the line below if you want to also push a specific version tag
          # docker push your-dockerhub-username/your-image-name:1.0.0